#!/bin/bash

plugins=(
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-autosuggestions
    MichaelAquilina/zsh-you-should-use
)

single_file_plugins=(
    ohmyzsh/ohmyzsh/master/plugins/jsontools/jsontools.plugin.zsh
    catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh
    ohmyzsh/ohmyzsh/master/plugins/history-substring-search/history-substring-search.zsh
    zap-zsh/vim/master/vim.plugin.zsh
)

add_plugins "${plugins[@]}"
add_plugins --singlefile "${single_file_plugins[@]}"
